/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as ApiPublicEmailIntakeRouteImport } from './routes/api/public/email-intake'
import { Route as ApiPublicSyncTimetableRouteImport } from './routes/api/public/sync-timetable'
import { Route as ApiPublicIcsTokenRouteImport } from './routes/api/public/ics/$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicEmailIntakeRoute = ApiPublicEmailIntakeRouteImport.update({
  id: '/api/public/email-intake',
  path: '/api/public/email-intake',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncTimetableRoute = ApiPublicSyncTimetableRouteImport.update({
  id: '/api/public/sync-timetable',
  path: '/api/public/sync-timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIcsTokenRoute = ApiPublicIcsTokenRouteImport.update({
  id: '/api/public/ics/$token',
  path: '/api/public/ics/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/api/public/email-intake': typeof ApiPublicEmailIntakeRoute
  '/api/public/sync-timetable': typeof ApiPublicSyncTimetableRoute
  '/api/public/ics/$token': typeof ApiPublicIcsTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/api/public/email-intake': typeof ApiPublicEmailIntakeRoute
  '/api/public/sync-timetable': typeof ApiPublicSyncTimetableRoute
  '/api/public/ics/$token': typeof ApiPublicIcsTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/api/public/email-intake': typeof ApiPublicEmailIntakeRoute
  '/api/public/sync-timetable': typeof ApiPublicSyncTimetableRoute
  '/api/public/ics/$token': typeof ApiPublicIcsTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/profile'
    | '/api/public/email-intake'
    | '/api/public/sync-timetable'
    | '/api/public/ics/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/profile'
    | '/api/public/email-intake'
    | '/api/public/sync-timetable'
    | '/api/public/ics/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/profile'
    | '/api/public/email-intake'
    | '/api/public/sync-timetable'
    | '/api/public/ics/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicEmailIntakeRoute: typeof ApiPublicEmailIntakeRoute
  ApiPublicSyncTimetableRoute: typeof ApiPublicSyncTimetableRoute
  ApiPublicIcsTokenRoute: typeof ApiPublicIcsTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/email-intake': {
      id: '/api/public/email-intake'
      path: '/api/public/email-intake'
      fullPath: '/api/public/email-intake'
      preLoaderRoute: typeof ApiPublicEmailIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-timetable': {
      id: '/api/public/sync-timetable'
      path: '/api/public/sync-timetable'
      fullPath: '/api/public/sync-timetable'
      preLoaderRoute: typeof ApiPublicSyncTimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ics/$token': {
      id: '/api/public/ics/$token'
      path: '/api/public/ics/$token'
      fullPath: '/api/public/ics/$token'
      preLoaderRoute: typeof ApiPublicIcsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicEmailIntakeRoute: ApiPublicEmailIntakeRoute,
  ApiPublicSyncTimetableRoute: ApiPublicSyncTimetableRoute,
  ApiPublicIcsTokenRoute: ApiPublicIcsTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
